### ISSUE TITLE
driver.copy offset runs out of bounds

### ISSUE THREAD

**Issue by skyne** [rudihorn/drm-vc4-grabber#3]
I'm trying to run this grabber prototype on an rPi 3 with osmc (5.10.32-2-osmc), Kodi19 and Hyperion 2.0.0-alpha.11

I've did some error countermeasures on my fork: https://github.com/skyne/drm-vc4-grabber

The only thing i cannot wrap my head around is that, after some time (1-2 minutes) the method driver.copy `mman::mmap` returns with an InvalidArgument error, doing some research i came into the conclusion that most probably the offset parameter is off.

I've did some specific logging, you can found it here: https://pastebin.com/6R4AMDzL

For me it looks like `self.mmap(handle)` returns with a constantly increasing value, until it reaches some limit then it crashes.

Also one more symptom: when this happens the video on Kodi freezes until i exit from the grabber.

Can you maybe help me set in some direction what can i take a look at?

After i can stabilize it (relative stability what i'm looking for) i'll be happy to create a PR to you from my fork, if you are interested.

**Comment by rudihorn** [comment]
This should be fixed with the 0.1.0 release.
