### ISSUE TITLE
drm-vc4-grabber crash when kodi is running video

### ISSUE THREAD

**Issue by konrul-r10** [rudihorn/drm-vc4-grabber#4]
Hello,

I am able to run "sudo ./drm-v4-capture -d /dev/dri/card1" in this path: "/drm-vc4-grabber-master/target/armv7-unknown-linux-gnueabihf/release" if there is no video playing on kodi.

However, when kodi is on and playing a video, the ssh output like this:

Setting color (when I see this message everything is working well with hyperion and less are running like ambient light of Philips)

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown { errno: ENOENT }', src/main.rs:141:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

How can I resolve this problem?

I am running RPi4 (4 GB RAM) with Raspberry Pi OS (Bullseye 11) 
Kodi v19.4 Matrix
(I am also using Node-Red, HAP-NodeJS, MotionEye)

My hyperion setup does not contain video grabber device, I am trying to use hyperion by "Screen Capture"

I am sorry if I messed up here when I try to explain my problem. 

Summary is: 

I got this error: 
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Unknown { errno: ENOENT }', src/main.rs:141:69
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

when I type this 
`sudo ./drm-v4-capture -d /dev/dri/card1`

Thanks in advance!

**Comment by rudihorn** [comment]
This should now be fixed with the 0.1.0 release.
